// AUTO-GENERATED from the channel-preview-design workflow (do not hand-edit the MAP;
// regenerate or tweak entries deliberately). Maps every (channel, assetType) to a
// platform-native preview archetype + the messaging keys that fill each UI slot.
import type { ChannelId } from './types'

export type PreviewArchetype = 'feed' | 'search' | 'display' | 'email' | 'landing' | 'blog' | 'lead' | 'notification'
export type PreviewFormat =
  | 'image' | 'video' | 'carousel' | 'text' | 'story' | 'reel' | 'poll' | 'link' | 'document' | 'collection' | 'product' | 'call'

export interface PreviewSpec {
  archetype: PreviewArchetype
  format: PreviewFormat
  /** UI slot -> messaging keys in priority order (first non-empty wins). */
  slots: Record<string, string[]>
}

const MAP: Record<string, PreviewSpec> = {
  'meta-ads:single-image': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['primary'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'meta-ads:carousel': { archetype: 'feed', format: 'carousel', slots: { "header": [], "body": ['primary'], "cardHeadlines": ['card1', 'card2', 'card3'], "description": ['description'], "cta": ['cta'] } },
  'meta-ads:video': { archetype: 'feed', format: 'video', slots: { "header": [], "body": ['primary'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'meta-ads:story': { archetype: 'feed', format: 'story', slots: { "header": [], "overlay": ['primary'], "cta": ['cta'] } },
  'meta-ads:reel': { archetype: 'feed', format: 'reel', slots: { "header": [], "overlay": ['primary'], "cta": ['cta'] } },
  'meta-ads:collection': { archetype: 'feed', format: 'collection', slots: { "header": [], "body": ['primary'], "overlay": ['collection-title'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'meta-ads:other': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['primary'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'instagram:feed': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['caption'] } },
  'instagram:carousel': { archetype: 'feed', format: 'carousel', slots: { "header": [], "body": ['caption'] } },
  'instagram:reel': { archetype: 'feed', format: 'reel', slots: { "header": [], "overlay": ['caption'] } },
  'instagram:story': { archetype: 'feed', format: 'story', slots: { "header": [], "overlay": ['caption'] } },
  'instagram:other': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['caption'] } },
  'facebook:text': { archetype: 'feed', format: 'text', slots: { "header": [], "body": ['body'] } },
  'facebook:image': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['body'] } },
  'facebook:video': { archetype: 'feed', format: 'video', slots: { "header": [], "body": ['body'] } },
  'facebook:link': { archetype: 'feed', format: 'link', slots: { "header": [], "body": ['body'] } },
  'facebook:reel': { archetype: 'feed', format: 'reel', slots: { "header": [], "overlay": ['body'] } },
  'facebook:story': { archetype: 'feed', format: 'story', slots: { "header": [], "overlay": ['body'] } },
  'facebook:other': { archetype: 'feed', format: 'text', slots: { "header": [], "body": ['body'] } },
  'linkedin-ads:single-image': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['intro'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'linkedin-ads:carousel': { archetype: 'feed', format: 'carousel', slots: { "header": [], "body": ['intro'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'linkedin-ads:video': { archetype: 'feed', format: 'video', slots: { "header": [], "body": ['intro'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'linkedin-ads:document': { archetype: 'feed', format: 'document', slots: { "header": [], "body": ['intro'], "headline": ['doc-title'], "cta": ['cta'] } },
  'linkedin-ads:thought-leader': { archetype: 'feed', format: 'text', slots: { "header": [], "body": ['intro'], "cta": ['cta'] } },
  'linkedin-ads:conversation': { archetype: 'notification', format: 'text', slots: { "body": ['message'], "cta": ['cta1', 'cta2'] } },
  'linkedin-ads:other': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['intro'], "headline": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'linkedin:text': { archetype: 'feed', format: 'text', slots: { "header": [], "body": ['body'] } },
  'linkedin:single-image': { archetype: 'feed', format: 'image', slots: { "header": [], "body": ['body'] } },
  'linkedin:document': { archetype: 'feed', format: 'document', slots: { "header": [], "body": ['body'] } },
  'linkedin:video': { archetype: 'feed', format: 'video', slots: { "header": [], "body": ['body'] } },
  'linkedin:poll': { archetype: 'feed', format: 'poll', slots: { "header": [], "body": ['body'] } },
  'linkedin:event': { archetype: 'feed', format: 'link', slots: { "header": [], "body": ['body'] } },
  'linkedin:other': { archetype: 'feed', format: 'text', slots: { "header": [], "body": ['body'] } },
  'x-ads:image': { archetype: 'feed', format: 'image', slots: { "body": ['post'], "cta": ['cta'] } },
  'x-ads:video': { archetype: 'feed', format: 'video', slots: { "body": ['post'], "cta": ['cta'] } },
  'x-ads:carousel': { archetype: 'feed', format: 'carousel', slots: { "body": ['post'], "cta": ['cta'] } },
  'x-ads:text': { archetype: 'feed', format: 'text', slots: { "body": ['post'], "cta": ['cta'] } },
  'x-ads:other': { archetype: 'feed', format: 'image', slots: { "body": ['post'], "cta": ['cta'] } },
  'x:text': { archetype: 'feed', format: 'text', slots: { "body": ['post'] } },
  'x:image': { archetype: 'feed', format: 'image', slots: { "body": ['post'] } },
  'x:video': { archetype: 'feed', format: 'video', slots: { "body": ['post'] } },
  'x:poll': { archetype: 'feed', format: 'poll', slots: { "body": ['post'] } },
  'x:thread': { archetype: 'feed', format: 'text', slots: { "body": ['post'] } },
  'x:other': { archetype: 'feed', format: 'text', slots: { "body": ['post'] } },
  'tiktok-ads:in-feed': { archetype: 'feed', format: 'video', slots: { "body": ['caption'], "cta": ['cta'] } },
  'tiktok-ads:spark': { archetype: 'feed', format: 'video', slots: { "body": ['caption'], "cta": ['cta'] } },
  'tiktok-ads:topview': { archetype: 'feed', format: 'video', slots: { "body": ['caption'], "cta": ['cta'] } },
  'tiktok-ads:carousel': { archetype: 'feed', format: 'carousel', slots: { "body": ['caption'], "cta": ['cta'] } },
  'tiktok-ads:other': { archetype: 'feed', format: 'video', slots: { "body": ['caption'], "cta": ['cta'] } },
  'tiktok:video': { archetype: 'feed', format: 'video', slots: { "body": ['caption'], "overlay": ['hook'] } },
  'tiktok:photo': { archetype: 'feed', format: 'carousel', slots: { "body": ['caption'] } },
  'tiktok:story': { archetype: 'feed', format: 'story', slots: { "body": ['caption'] } },
  'tiktok:other': { archetype: 'feed', format: 'video', slots: { "body": ['caption'] } },
  'youtube-ads:skippable': { archetype: 'display', format: 'video', slots: { "overlay": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'youtube-ads:non-skippable': { archetype: 'display', format: 'video', slots: { "overlay": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'youtube-ads:bumper': { archetype: 'display', format: 'video', slots: { "overlay": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'youtube-ads:in-feed': { archetype: 'display', format: 'video', slots: { "overlay": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'youtube-ads:shorts': { archetype: 'display', format: 'video', slots: { "overlay": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'youtube-ads:other': { archetype: 'display', format: 'video', slots: { "overlay": ['headline'], "description": ['description'], "cta": ['cta'] } },
  'youtube:long-form': { archetype: 'feed', format: 'video', slots: { "header": ['title'], "body": ['description'] } },
  'youtube:short': { archetype: 'feed', format: 'video', slots: { "overlay": ['title'], "body": ['description'] } },
  'youtube:live': { archetype: 'feed', format: 'video', slots: { "header": ['title'], "body": ['description'] } },
  'youtube:community': { archetype: 'feed', format: 'text', slots: { "body": ['description'], "header": ['title'] } },
  'youtube:other': { archetype: 'feed', format: 'video', slots: { "header": ['title'], "body": ['description'] } },
  'pinterest-ads:standard': { archetype: 'feed', format: 'image', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'pinterest-ads:video': { archetype: 'feed', format: 'video', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'pinterest-ads:carousel': { archetype: 'feed', format: 'carousel', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'pinterest-ads:collection': { archetype: 'feed', format: 'collection', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'pinterest-ads:idea': { archetype: 'feed', format: 'story', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'pinterest-ads:other': { archetype: 'feed', format: 'image', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'pinterest:standard': { archetype: 'feed', format: 'image', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'] } },
  'pinterest:video': { archetype: 'feed', format: 'video', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'] } },
  'pinterest:idea': { archetype: 'feed', format: 'story', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'] } },
  'pinterest:carousel': { archetype: 'feed', format: 'carousel', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'] } },
  'pinterest:other': { archetype: 'feed', format: 'image', slots: { "overlay": ['title'], "headline": ['title'], "description": ['description'] } },
  'snapchat-ads:single': { archetype: 'feed', format: 'story', slots: { "header": ['brand'], "overlay": ['headline'], "headline": ['headline'], "cta": ['cta'] } },
  'snapchat-ads:story': { archetype: 'feed', format: 'story', slots: { "header": ['brand'], "overlay": ['headline'], "headline": ['headline'], "cta": ['cta'] } },
  'snapchat-ads:collection': { archetype: 'feed', format: 'collection', slots: { "header": ['brand'], "overlay": ['headline'], "headline": ['headline'], "cta": ['cta'] } },
  'snapchat-ads:dynamic': { archetype: 'feed', format: 'product', slots: { "header": ['brand'], "overlay": ['headline'], "headline": ['headline'], "cta": ['cta'] } },
  'snapchat-ads:other': { archetype: 'feed', format: 'story', slots: { "header": ['brand'], "overlay": ['headline'], "headline": ['headline'], "cta": ['cta'] } },
  'reddit-ads:image': { archetype: 'feed', format: 'image', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'reddit-ads:video': { archetype: 'feed', format: 'video', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'reddit-ads:carousel': { archetype: 'feed', format: 'carousel', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'reddit-ads:text': { archetype: 'feed', format: 'text', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'reddit-ads:other': { archetype: 'feed', format: 'text', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'google-search:rsa': { archetype: 'search', format: 'text', slots: { "header": ['business'], "url": ['path'], "headline": ['h1', 'h2', 'h3'], "description": ['d1', 'd2'] } },
  'google-search:call': { archetype: 'search', format: 'call', slots: { "header": ['business'], "headline": ['h1', 'h2'], "description": ['d1'] } },
  'google-search:dsa': { archetype: 'search', format: 'text', slots: { "headline": ['d1'], "description": ['d1', 'd2'] } },
  'google-search:other': { archetype: 'search', format: 'text', slots: { "headline": ['headline'], "description": ['description'], "url": ['path'] } },
  'google-demand:image': { archetype: 'display', format: 'image', slots: { "header": ['business'], "overlay": ['long-headline', 'headline'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'google-demand:video': { archetype: 'display', format: 'video', slots: { "header": ['business'], "overlay": ['long-headline', 'headline'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'google-demand:carousel': { archetype: 'display', format: 'carousel', slots: { "header": ['business'], "headline": ['headline'], "body": ['description'], "cardHeadlines": ['long-headline', 'headline'], "cta": ['cta'] } },
  'google-demand:product': { archetype: 'display', format: 'product', slots: { "header": ['business'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'google-demand:other': { archetype: 'display', format: 'image', slots: { "header": ['business'], "overlay": ['long-headline', 'headline'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'pmax:image-group': { archetype: 'display', format: 'image', slots: { "header": ['business'], "overlay": ['long-headline', 'headline'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'pmax:video-group': { archetype: 'display', format: 'video', slots: { "header": ['business'], "overlay": ['long-headline', 'headline'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'pmax:product-feed': { archetype: 'display', format: 'product', slots: { "header": ['business'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'pmax:other': { archetype: 'display', format: 'image', slots: { "header": ['business'], "overlay": ['long-headline', 'headline'], "headline": ['headline'], "body": ['description'], "cta": ['cta'] } },
  'email:newsletter': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "body": ['body'], "cta": ['cta'] } },
  'email:nurture': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "overlay": ['headline'], "body": ['body'], "cta": ['cta'] } },
  'email:promotional': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "overlay": ['headline'], "body": ['body'], "cta": ['cta'] } },
  'email:announcement': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "overlay": ['headline'], "body": ['body'], "cta": ['cta'] } },
  'email:welcome': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "overlay": ['headline'], "body": ['body'], "cta": ['cta'] } },
  'email:re-engagement': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "overlay": ['headline'], "body": ['body'], "cta": ['cta'] } },
  'email:other': { archetype: 'email', format: 'text', slots: { "subject": ['subject'], "preview": ['preview'], "overlay": ['headline'], "body": ['body'], "cta": ['cta'] } },
  'sms:promotional': { archetype: 'notification', format: 'text', slots: { "body": ['message'], "url": ['link'] } },
  'sms:transactional': { archetype: 'notification', format: 'text', slots: { "body": ['message'], "url": ['link'] } },
  'sms:reminder': { archetype: 'notification', format: 'text', slots: { "body": ['message'], "url": ['link'] } },
  'sms:alert': { archetype: 'notification', format: 'text', slots: { "body": ['message'], "url": ['link'] } },
  'sms:other': { archetype: 'notification', format: 'text', slots: { "body": ['message'], "url": ['link'] } },
  'push:promotional': { archetype: 'notification', format: 'text', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'push:transactional': { archetype: 'notification', format: 'text', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'push:reminder': { archetype: 'notification', format: 'text', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'push:other': { archetype: 'notification', format: 'text', slots: { "header": ['title'], "body": ['body'], "cta": ['cta'] } },
  'blog:article': { archetype: 'blog', format: 'text', slots: { "headline": ['title'], "description": ['meta-description'], "body": ['body'] } },
  'blog:pillar': { archetype: 'blog', format: 'document', slots: { "headline": ['title'], "description": ['meta-description'], "body": ['body'] } },
  'blog:listicle': { archetype: 'blog', format: 'text', slots: { "headline": ['title'], "description": ['meta-description'], "body": ['body'] } },
  'blog:case-study': { archetype: 'blog', format: 'text', slots: { "headline": ['title'], "description": ['meta-description'], "body": ['body'] } },
  'blog:other': { archetype: 'blog', format: 'text', slots: { "headline": ['title'], "description": ['meta-description'], "body": ['body'] } },
  'landing-page:lead-capture': { archetype: 'landing', format: 'text', slots: { "headline": ['headline'], "description": ['subhead'], "body": ['body'], "cta": ['cta'] } },
  'landing-page:sales': { archetype: 'landing', format: 'text', slots: { "headline": ['headline'], "description": ['subhead'], "body": ['body'], "proof": ['proof'], "cta": ['cta'] } },
  'landing-page:webinar-reg': { archetype: 'landing', format: 'text', slots: { "headline": ['headline'], "meta": ['when'], "body": ['body'], "cta": ['cta'] } },
  'landing-page:waitlist': { archetype: 'landing', format: 'text', slots: { "headline": ['headline'], "description": ['subhead'], "body": ['body'], "cta": ['cta'] } },
  'landing-page:other': { archetype: 'landing', format: 'text', slots: { "headline": ['headline'], "description": ['subhead'], "body": ['body'], "cta": ['cta'] } },
  'lead-magnet:ebook': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "description": ['subtitle', 'description'], "body": ['description'], "cta": ['cta'] } },
  'lead-magnet:whitepaper': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'lead-magnet:checklist': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'lead-magnet:template': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'lead-magnet:webinar': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "meta": ['when'], "description": ['description'], "cta": ['cta'] } },
  'lead-magnet:cheat-sheet': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
  'lead-magnet:other': { archetype: 'lead', format: 'document', slots: { "headline": ['title'], "description": ['description'], "cta": ['cta'] } },
}

const FALLBACK: PreviewSpec = { archetype: 'feed', format: 'text', slots: { body: ['body', 'primary', 'caption'] } }

/** The platform-native preview spec for an asset, by channel + type. */
export function previewSpec(channel: ChannelId, assetType?: string): PreviewSpec {
  return MAP[channel + ":" + assetType] ?? MAP[channel + ":other"] ?? FALLBACK
}
